### ISSUE TITLE
firetable init <folder> throws an error

### ISSUE THREAD

**Issue by mtford90** [rowyio/rowy#263]
**Describe the bug**

```
➜  packages git:(master) ✗ firetable init xyz      
node     12.19.0
git      2.24.3
yarn     1.22.1
firebase 8.15.1
🛑 FAILED
Error: You must provide a `choices` parameter
    at ListPrompt.throwParamError (/Users/mtford/.config/yarn/global/node_modules/firetable/node_modules/inquirer/lib/prompts/base.js:79:11)
    at new ListPrompt (/Users/mtford/.config/yarn/global/node_modules/firetable/node_modules/inquirer/lib/prompts/list.js:26:12)
    at PromptUI.fetchAnswer (/Users/mtford/.config/yarn/global/node_modules/firetable/node_modules/inquirer/lib/ui/prompt.js:100:25)
    at MergeMapSubscriber._tryNext (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)

```

**To Reproduce**

Run `firebase init <folder>`

**Expected behavior**

It creates the project in `<folder>`.

Or at least indicates what the `choices` parameter is supposed to contain.

**Additional context**

```
➜  packages git:(master) ✗ firetable -V       
1.1.6
```

**Comment by notsidney** [comment]
Hi @mtford90, what was the message before you got the error? Did you get to the “Getting your Firebase projects” message?

**Comment by mtford90** [comment]
@notsidney that's correct

Here's the raw stdout output:

```
^[[2J^[[0f++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++            ++++
++++++++++++++++++++++++     A      ++++
++++++++++++++++++++++++   AA AA    ++++
++++++++++++++++++++++++  AA   AA   ++++
++++++++++++++++++++++++ AAA   AAA  ++++
++++++++++++++                      ++++
++++++++++++++  ++++++++  +++++++   ++++
++++++++++++++  ++++++++  +++++++   ++++
++++++++++++++  ++++++++  +++++++   ++++
++++                                ++++
++++   +++++++  ++++++++  +++++++   ++++
++++   +++++++  ++++++++  +++++++   ++++
++++   +++++++  ++++++++  +++++++   ++++
++++                                ++++
++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++
 _______  _  ______   _______  _______  _______  ______   _        _______
(_______)| |(_____ \ (_______)(_______)(_______)(____  \ (_)      (_______)
 _____   | | _____) ) _____       _     _______  ____)  ) _        _____
|  ___)  | ||  __  / |  ___)     | |   |  ___  ||  __  ( | |      |  ___)
| |      | || |  \ \ | |_____    | |   | |   | || |__)  )| |_____ | |_____
|_|      |_||_|   |_||_______)   |_|   |_|   |_||______/ |_______)|_______)

^[[0G  ^[[96m◜ ^[[90mChecking versions of required system packages^[[0m^[[0G  ^[[96m◠ ^[[90mChecking versions of required system packages^[[0m^[[0G  ^[[96m◝ ^[[90mChecking versions of required system packages^[[0m^[[0G  ^[[96m◞ ^[[90mChecking versions of required system packages^[[0m^[[0G  ^[[96m◡ ^[[90mChecking versions of required system packages^[[0m^[[0G  ^[[96m◟ ^[[90mChecking versions of required system packages^[[0m^[[0G  ^[[96m◜ ^[[90mChecking versions of required system packages^[[0m^[[0G  ^[[96m◠ ^[[90mChecking versions of required system packages^[[0m^[[0G  ^[[96m◝ ^[[90mChecking versions of required system packages^[[0m^[[0G  ^[[96m◞ ^[[90mChecking versions of required system packages^[[0m^[[0G  ^[[96m◡ ^[[90mChecking versions of required system packages^[[0m^[[0G  ^[[96m◟ ^[[90mChecking versions of required system packages^[[0m^[[0G^[[2Knode     12.19.0
git      2.24.3
yarn     1.22.1
firebase 8.15.1
^[[0G  ^[[96m◜ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◠ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◝ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◞ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◡ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◟ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◜ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◠ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◝ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◞ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◡ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◟ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◜ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◠ ^[[90mGetting your Firebase projects^[[0m^[[0G  ^[[96m◝ ^[[90mGetting your Firebase projects^[[0m^[[0G^[[2K🛑 FAILED
Error: You must provide a `choices` parameter
    at ListPrompt.throwParamError (/Users/mtford/.config/yarn/global/node_modules/firetable/node_modules/inquirer/lib/prompts/base.js:79:11)
    at new ListPrompt (/Users/mtford/.config/yarn/global/node_modules/firetable/node_modules/inquirer/lib/prompts/list.js:26:12)
    at PromptUI.fetchAnswer (/Users/mtford/.config/yarn/global/node_modules/firetable/node_modules/inquirer/lib/ui/prompt.js:100:25)
    at MergeMapSubscriber._tryNext (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/Users/mtford/.config/yarn/global/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
```

**Comment by mtford90** [comment]
Oh - weird.

So I only see this error if I try to initialise firetable within my monorepo.

If I initialise elsewhere on the filesystem, it seems to be fine....

**Comment by notsidney** [comment]
@mtford90 can you try running `firebase projects:list` in that monorepo folder?

**Comment by mtford90** [comment]
@notsidney yep - there's a slight difference, namely the addition of `(current)`

Monorepo:

```
➜  packages git:(master) firebase projects:list 
✔ Preparing the list of your Firebase projects
┌──────────────────────┬────────────────────────────┬────────────────┬──────────────────────┐
│ Project Display Name │ Project ID                 │ Project Number │ Resource Location ID │
├──────────────────────┼────────────────────────────┼────────────────┼──────────────────────┤
│ xxxxx-xxxx           │ xxxxx-xxxx-xxxxx (current) │ xxxxxxxxxxxx   │ europe-west          │
└──────────────────────┴────────────────────────────┴────────────────┴──────────────────────┘

1 project(s) total.

```

Elsewhere on the file system:

```
➜  Playground firebase projects:list
✔ Preparing the list of your Firebase projects
┌──────────────────────┬──────────────────┬────────────────┬──────────────────────┐
│ Project Display Name │ Project ID       │ Project Number │ Resource Location ID │
├──────────────────────┼──────────────────┼────────────────┼──────────────────────┤
│ xxxxx-xxxx           │ xxxxx-xxxx-xxxxx │ xxxxxxxxxxxx   │ europe-west          │
└──────────────────────┴──────────────────┴────────────────┴──────────────────────┘

1 project(s) total.

```

**Comment by shamsmosowi** [comment]
Potentially a regex issue, I'll look into it

**Comment by rapejim** [comment]
@mtford90 Did you tried relogin on firebase-CLI, typing `firebase logout` and `firebase login`?

**Comment by shamsmosowi** [comment]
you can use the cloud run deploy button that runs in cloud shell, Which provides a more consistent environment
